# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/execode',
                'doc_host': 'https://tongyx361.github.io',
                'git_url': 'https://github.com/tongyx361/execode',
                'lib_path': 'execode'},
  'syms': { 'execode.core': { 'execode.core.CodeExecCfg': ('core.html#codeexeccfg', 'execode/core.py'),
                              'execode.core.CodeExecCfg.__init__': ('core.html#codeexeccfg.__init__', 'execode/core.py'),
                              'execode.core.CodeExecCfg.extract_cells': ('core.html#codeexeccfg.extract_cells', 'execode/core.py'),
                              'execode.core.CodeExecCfg.load_from_id_or_path': ( 'core.html#codeexeccfg.load_from_id_or_path',
                                                                                 'execode/core.py'),
                              'execode.core.CodeExecCfg.no_cells_todo': ('core.html#codeexeccfg.no_cells_todo', 'execode/core.py'),
                              'execode.core.CodeExecCfg.wrap_output': ('core.html#codeexeccfg.wrap_output', 'execode/core.py'),
                              'execode.core.exec_cells': ('core.html#exec_cells', 'execode/core.py')}}}
